# Generated by Django 3.2.6 on 2021-09-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sobre',
        ),
        migrations.AddField(
            model_name='customuser',
            name='aniversario',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='genero_choices',
            field=models.CharField(choices=[('F', 'Feminino'), ('H', 'Masculino'), ('O', 'Outro')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ocupacao',
            field=models.CharField(choices=[('e', 'Estudante'), ('t', 'Trabalha na área')], default='Estudante', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
