# Generated by Django 3.2.6 on 2021-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210907_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='genero_choices',
            new_name='genero',
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
