# Generated by Django 3.2.6 on 2021-09-08 16:09

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210907_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True),
        ),
    ]
