# Generated by Django 3.2.6 on 2021-09-08 16:12

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_customuser_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CEP',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True),
        ),
    ]
