# Generated by Django 3.2.6 on 2021-09-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210910_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='link_ig',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
