# Generated by Django 3.2.6 on 2021-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_customuser_link_ig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, default='static/img/default_profile_image.jpg', null=True, upload_to='static/img/'),
        ),
    ]
