# Generated by Django 3.2.6 on 2021-10-06 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0011_alter_customuser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seguidores',
            field=models.ManyToManyField(blank=True, null=True, related_name='Seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('s', 'Seguir'), ('n', 'Não Seguir')], default='Segui', max_length=10)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL)),
                ('seguindo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguindo', to='usuarios.customuser')),
            ],
            options={
                'unique_together': {('seguidor', 'seguindo')},
            },
        ),
    ]
