# Generated by Django 3.2.6 on 2021-10-07 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0012_auto_20211006_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='Seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
