# Generated by Django 3.2.6 on 2021-10-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_customuser_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='seguir',
            name='seguidores',
            field=models.ManyToManyField(related_name='seguidores', to='usuarios.CustomUser'),
        ),
        migrations.AddField(
            model_name='seguir',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguido', to='usuarios.customuser'),
        ),
        migrations.AlterField(
            model_name='seguir',
            name='value',
            field=models.CharField(choices=[('s', 'Seguir'), ('n', 'Não Seguir')], default='Seguir', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='seguir',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='seguir',
            name='seguidor',
        ),
        migrations.RemoveField(
            model_name='seguir',
            name='seguindo',
        ),
    ]
