# Generated by Django 3.2.6 on 2021-10-11 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0014_auto_20211010_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='Seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguir',
            name='seguidores',
            field=models.ManyToManyField(related_name='seguidor', to='usuarios.CustomUser'),
        ),
    ]
