# Generated by Django 3.2.6 on 2021-10-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20211010_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seguidores',
        ),
    ]
