# Generated by Django 3.2.6 on 2021-10-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_customuser_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguir',
            name='value',
        ),
    ]
