# Generated by Django 3.2.6 on 2021-10-13 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0017_remove_seguir_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='Seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
