# Generated by Django 3.2.6 on 2021-10-13 02:51

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_customuser_seguindo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='CEP',
            field=localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ocupacao',
            field=models.CharField(choices=[('Estudante', 'Estudante'), ('Trabalha na área', 'Trabalha na área')], default='Estudante', max_length=20),
        ),
    ]
