# Generated by Django 3.2.6 on 2021-08-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
