# Generated by Django 3.2.6 on 2021-08-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_created_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_in',
            field=models.DateField(auto_now=True),
        ),
    ]
