# Generated by Django 3.2.6 on 2021-08-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_created_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_in',
            field=models.DateTimeField(),
        ),
    ]
