# Generated by Django 3.2.6 on 2021-08-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_created_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('python', 'PYTHON'), ('html', 'HTML'), ('css', 'CSS')], default='python', max_length=10),
        ),
    ]
