# Generated by Django 3.2.6 on 2021-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'PYTHON'), ('HTML', 'HTML'), ('CSS', 'CSS')], default='Python', max_length=10),
        ),
    ]
