# Generated by Django 3.2.6 on 2021-08-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210816_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacao', models.CharField(choices=[('livro', 'Livro'), ('curso', 'Curso')], default='curso', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('created_in', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
