# Generated by Django 3.2.4 on 2021-08-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_indicacao_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacao',
            name='indicacao',
            field=models.CharField(choices=[('l', 'Livro'), ('c', 'Curso')], default='curso', max_length=10),
        ),
    ]
