# Generated by Django 3.2.6 on 2021-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_indicacao_indicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicacao',
            options={'verbose_name': 'Indicação', 'verbose_name_plural': 'Indicações'},
        ),
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
