# Generated by Django 3.2.4 on 2021-08-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210823_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='link_venda',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
