# Generated by Django 3.2.4 on 2021-08-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_indicacao_link_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicacao',
            old_name='link_venda',
            new_name='link',
        ),
        migrations.AddField(
            model_name='indicacao',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
