# Generated by Django 3.2.6 on 2021-08-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
