# Generated by Django 3.2.4 on 2021-08-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_post_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitulo',
        ),
    ]
