# Generated by Django 3.2.4 on 2021-09-08 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_post_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
