# Generated by Django 3.2.6 on 2021-09-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_post_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='aprovado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
