# Generated by Django 3.2.6 on 2021-09-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210908_1248'),
        ('main', '0030_auto_20210908_1309'),
    ]

    operations = [
    ]
