# Generated by Django 3.2.6 on 2021-09-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_customuser_cidade'),
        ('main', '0031_merge_0030_auto_20210908_1248_0030_auto_20210908_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='posts',
            new_name='post',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='avaliacao',
            field=models.CharField(choices=[('g', 'Gostei'), ('n', 'Não Gostei')], default='Gostei', max_length=200),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='comentarios',
            unique_together={('post', 'usuario')},
        ),
    ]
