# Generated by Django 3.2.6 on 2021-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210909_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='deslike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
