# Generated by Django 3.2.6 on 2021-09-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210910_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='deslike',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='like',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='interacao',
            field=models.CharField(blank=True, choices=[('G', 'Gostei'), ('N', 'Não gostei')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
