# Generated by Django 3.2.6 on 2021-09-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='foto',
        ),
    ]
