# Generated by Django 3.2.6 on 2021-09-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_post_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
    ]
