# Generated by Django 3.2.6 on 2021-09-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='foto',
        ),
    ]
