# Generated by Django 3.2.6 on 2021-09-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_indicacao_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='interacao',
        ),
    ]
