# Generated by Django 3.2.6 on 2021-09-30 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0045_remove_comentarios_interacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(blank=True, default=None, related_name='Curtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Curtir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(choices=[('g', 'Gostei'), ('n', 'Não Gostei')], default='Gostei', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
