# Generated by Django 3.2.6 on 2021-10-10 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_customuser_seguidores'),
        ('main', '0046_auto_20210930_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser'),
        ),
    ]
