# Generated by Django 3.2.6 on 2021-10-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_comentarios_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={},
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
