# Generated by Django 3.2.6 on 2021-10-10 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20211010_2039'),
        ('main', '0049_auto_20211010_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('comentario', models.TextField(blank=True, null=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser')),
            ],
        ),
    ]
