# Generated by Django 3.2.6 on 2021-10-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='teste',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
