# Generated by Django 3.2.6 on 2021-10-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_publicacao_comentario'),
        ('comentarios', '0003_auto_20211002_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='publicacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacao', to='social.publicacao'),
        ),
    ]
