# Generated by Django 3.2.6 on 2021-09-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_posts_publicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
