# Generated by Django 3.2.6 on 2021-09-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_customuser_link_ig'),
        ('social', '0003_alter_publicacao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.customuser'),
        ),
    ]
