# Generated by Django 3.2.6 on 2021-09-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
