# Generated by Django 3.2.6 on 2021-10-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20211001_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
