# Generated by Django 3.2.6 on 2021-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('social', '0009_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='comentario',
            field=models.ManyToManyField(blank=True, null=True, related_name='comentarios_social', to='comentarios.Comentario'),
        ),
    ]
