# Generated by Django 3.2.6 on 2021-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('social', '0010_publicacao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='comentario',
            field=models.ManyToManyField(related_name='comentarios_social', to='comentarios.Comentario'),
        ),
    ]
