# Generated by Django 3.2.6 on 2021-10-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_comentario_publicacao'),
        ('social', '0011_alter_publicacao_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='comentario',
        ),
        migrations.AddField(
            model_name='publicacao',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_social', to='comentarios.comentario'),
        ),
    ]
