# Generated by Django 3.2.6 on 2021-10-03 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20211003_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='comentario',
        ),
    ]
