# Generated by Django 3.2.6 on 2021-10-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_publicacao_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='comentario',
        ),
    ]
