# Generated by Django 3.2.6 on 2021-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_remove_publicacao_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
